#!/usr/bin/env Rscript
# Generate the C Unicode classes used by the LFM2 pre-tokenizer.
# Rscript scripts/generate_tokenizer_unicode.R [data-dir] [output-header]
# Input: Unicode 17.0.0 UCD; pinned MD5 checksums validate the downloaded files.
args <- commandArgs(trailingOnly = TRUE)
data_dir <- if (length(args) > 0L) args[[1L]] else "build/unicode-data"
output <- if (length(args) > 1L) args[[2L]] else "src/tokenizer_unicode.h"
checksums <- c(DerivedCoreProperties.txt = "2ce17dcc2954bb28a298854b535a6836",
               PropList.txt = "d1c4ecf7da205e937fd56b7a5bb2e6d6",
               UnicodeData.txt = "959cb19fcda0240caef8c02953e3d771")
dir.create(data_dir, recursive = TRUE, showWarnings = FALSE)
paths <- file.path(data_dir, names(checksums))
for (i in seq_along(paths)) {
  if (!file.exists(paths[[i]])) {
    download.file(paste0("https://www.unicode.org/Public/17.0.0/ucd/", names(checksums)[[i]]),
                  paths[[i]], mode = "wb", quiet = TRUE)
  }
}
stopifnot(identical(unname(tools::md5sum(paths)), unname(checksums)))
property_ranges <- function(path, property) {
  lines <- sub("#.*$", "", readLines(path, warn = FALSE))
  fields <- strsplit(lines, ";", fixed = TRUE)
  selected <- vapply(fields, function(x) length(x) == 2L && trimws(x[[2L]]) == property, logical(1))
  ranges <- lapply(fields[selected], function(x) {
    limits <- strsplit(trimws(x[[1L]]), "..", fixed = TRUE)[[1L]]
    values <- strtoi(limits, base = 16L)
    c(values[[1L]], tail(values, 1L))
  })
  do.call(rbind, ranges)
}
coalesce <- function(ranges) {
  ranges <- ranges[order(ranges[, 1L]), , drop = FALSE]
  result <- matrix(0L, nrow(ranges), 2L)
  used <- 0L
  for (i in seq_len(nrow(ranges))) {
    if (used > 0L && ranges[i, 1L] <= result[used, 2L] + 1L) {
      result[used, 2L] <- max(result[used, 2L], ranges[i, 2L])
    } else {
      used <- used + 1L
      result[used, ] <- ranges[i, ]
    }
  }
  result[seq_len(used), , drop = FALSE]
}
ucd <- strsplit(readLines(paths[[3L]], warn = FALSE), ";", fixed = TRUE)
numeric_rows <- vapply(ucd, function(x) x[[3L]] %in% c("Nd", "Nl", "No"), logical(1))
cp <- vapply(ucd[numeric_rows], function(x) strtoi(x[[1L]], base = 16L), integer(1))
classes <- list(alphabetic = property_ranges(paths[[1L]], "Alphabetic"),
                numeric = cbind(cp, cp), whitespace = property_ranges(paths[[2L]], "White_Space"))
lines <- "/* Unicode 17.0.0; generated by scripts/generate_tokenizer_unicode.R. */"
for (name in names(classes)) {
  ranges <- coalesce(classes[[name]])
  lines <- c(lines, paste0("static const uint32_t unicode_", name, "[][2] = {"),
             sprintf("    {0x%x, 0x%x},", ranges[, 1L], ranges[, 2L]), "};")
}
writeLines(lines, output, useBytes = TRUE)
cat("Generated ", output, " from pinned Unicode 17.0.0 data\n", sep = "")
